global using Copper68k;
global using CopperMod.Amiga.Bus;
global using CopperMod.Amiga.Core;
global using CopperMod.Amiga.CustomChips.Agnus;
global using CopperMod.Amiga.CustomChips.Cia;
global using CopperMod.Amiga.CustomChips.Denise;
global using CopperMod.Amiga.CustomChips.Paula;
global using CopperMod.Amiga.Diagnostics;
global using CopperMod.Amiga.Firmware;
global using CopperMod.Amiga.Runtime;
global using AmigaBus = CopperMod.Amiga.Bus.Bus;
global using AmigaCia = CopperMod.Amiga.CustomChips.Cia.Cia;
